# Copy this file as "local.config.yaml" in the same folder (.gitignored)
# Enable Google Picker API and test port

# The developer key needed for the picker API
# Credentials/API Keys
developerKey: [ENTER_YOUR_DEVELOPER_KEY]
# The Client ID obtained from the Google Cloud Console.
# Credentials/OAuth 2.0 Client IDs
clientId: [ENTER_YOUR_CLIENT_ID.apps.googleusercontent.com]
clientSecret: [ENTER_YOUR_CLIENT_SECRET]