name: tekartik_google_jsapi_picker
description: file picker api
dependencies:
  bootstrap_for_pub: any
  browser: any
  tekartik_google_jsapi:
    git: https://github.com/alextekartik/google-jsapi.dart
dev_dependencies:
  unittest: any
