name: tekartik_google_jsapi_picker
version: 0.2.2+1
description: file picker api
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  tekartik_google_jsapi:
    git:
      url: https://github.com/alextekartik/google-jsapi.dart
      ref: dart2_3
    version: '>=0.2.0'
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
  http:
dev_dependencies:
  yaml:
  dev_test:
  tekartik_bootstrap:
    git:
      url: https://github.com/tekartik/bootstrap.dart
      ref: dart2_3
    version: '>=0.3.0'
  build_runner:
  build_test:
  build_web_compilers:
  test: any
  process_run: '>=0.10.2'
  googleapis_auth: '>=0.2.10'
  chrome_travis:
    git:
      url: https://github.com/tekartik/chrome_travis.dart
      ref: dart2_3
    version: '>=0.1.4'