name: tekartik_google_jsapi_picker
version: 0.1.0
description: file picker api
dependencies:
  browser: any
  tekartik_google_jsapi:
    git: https://github.com/alextekartik/google-jsapi.dart
dev_dependencies:
  bootstrap: any
  test: any
dependency_overrides:
#  tekartik_google_jsapi:
#    path: ../google-jsapi.dart